<a href="https://colab.research.google.com/github/shahrukhalam1011-unisa/Training_flatplanet_pytorch/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensors

In [2]:
import torch
import numpy as np

# Lists

In [4]:
my_list= [[1,2,3,4,5], [5,6,4,74,4]]
my_list

[[1, 2, 3, 4, 5], [5, 6, 4, 74, 4]]

# Numpy arrays

In [8]:
np1=np.random.rand(3,3)
np1


array([[0.58925578, 0.64499875, 0.75021213],
       [0.20324845, 0.31596558, 0.53072069],
       [0.38616365, 0.59491318, 0.19660554]])

In [9]:
np1.dtype

dtype('float64')

# Tensors

In [10]:
tensor_2d = torch.randn(3,3)
tensor_2d

tensor([[ 0.5010,  2.0861,  1.6203],
        [ 0.1077,  0.8079,  0.1613],
        [ 1.9293,  0.2148, -0.2272]])

In [12]:
tensor_3d=torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])